# Generated by Django 6.0.7 on 2026-07-13 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('steam', 'Steam'), ('faceit', 'Faceit'), ('opendota', 'OpenDota'), ('manual', 'Manual')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime_forever', models.IntegerField(help_text='в минутах')),
                ('date', models.DateField()),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='profiles.gameaccount')),
            ],
            options={
                'unique_together': {('game_account', 'date')},
            },
        ),
    ]
