# Generated by Django 6.0.7 on 2026-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysnapshot',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='dailysnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailysnapshot',
            name='appid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysnapshot',
            name='game_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='playtime_forever',
            field=models.IntegerField(help_text='в минутах, общее время на момент снимка'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysnapshot',
            unique_together={('game_account', 'appid', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='gameaccount',
            unique_together={('platform', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='dailysnapshot',
            index=models.Index(fields=['game_account', 'date'], name='profiles_da_game_ac_a5522e_idx'),
        ),
    ]
