# Generated by Django 6.0.7 on 2026-07-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_dailysnapshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
