# Generated by Django 6.0.7 on 2026-07-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_gameaccount_avatar_gameaccount_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='game_label',
            field=models.CharField(blank=True, help_text='Человекочитаемое название игры для лидерборда', max_length=50),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='skill_rating',
            field=models.IntegerField(blank=True, help_text='ELO/MMR — если платформа его даёт', null=True),
        ),
    ]
