# Generated by Django 6.0.7 on 2026-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_gameaccount_game_label_gameaccount_skill_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='extra_stats',
            field=models.JSONField(blank=True, help_text='Доп. статистика: winrate, топ герои и т.д.', null=True),
        ),
    ]
