# Generated by Django 6.0.7 on 2026-07-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_gameaccount_extra_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='platform',
            field=models.CharField(choices=[('steam', 'Steam'), ('faceit', 'Faceit'), ('opendota', 'OpenDota'), ('pubg', 'PUBG'), ('manual', 'Manual')], max_length=20),
        ),
    ]
