# Generated by Django 6.0.7 on 2026-07-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_gameaccount_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='platform',
            field=models.CharField(choices=[('steam', 'Steam'), ('faceit', 'Faceit'), ('opendota', 'OpenDota'), ('lol', 'League of Legends'), ('valorant', 'Valorant'), ('pubg', 'PUBG'), ('roblox', 'Roblox'), ('manual', 'Manual')], max_length=20),
        ),
    ]
