# Generated by Django 6.0.7 on 2026-08-31 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_clanactivity_favoriteplayer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanactivity',
            name='kind',
            field=models.CharField(choices=[('joined', 'Joined'), ('match', 'Match'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='clanactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
