# Generated by Django 6.0.7 on 2026-08-31 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_clanactivity_kind_alter_clanactivity_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteplayer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteplayer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoriteplayer',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='favoriteplayer',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='favoriteplayer',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='favoriteplayer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites_owned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteplayer',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='favoriteplayer',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favoriteplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('target_user__isnull', False)), fields=('owner', 'target_user'), name='uniq_favorite_owner_user'),
        ),
        migrations.AddConstraint(
            model_name='favoriteplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('owner', 'platform', 'external_id'), name='uniq_favorite_owner_external'),
        ),
        migrations.RemoveField(
            model_name='favoriteplayer',
            name='target',
        ),
        migrations.RemoveField(
            model_name='favoriteplayer',
            name='user',
        ),
    ]
