# Generated by Django 6.0.7 on 2026-09-05 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lfg_response', 'LFG response'), ('clan_join', 'Clan join'), ('clan_message', 'Clan message'), ('favorite_lfg', 'Favorite LFG'), ('weekly', 'Weekly report'), ('system', 'System')], default='system', max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=280)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
